# All possible outputs from this workflow when given a feature-barcode matrix.
all:
  - "mtx.h5ad"
  - "mtx_qcseurat.h5ad"
  - "mtx_qcseurat_pca.h5ad"
  - "mtx_qcseurat_umap.h5ad"
  - "mtx_qcseurat_tsne.h5ad"
  - "mtx_qcseurat_leiden.h5ad"