# Example config file for end user.

# User-defined input. The path must be either absolute or relative to the 
# working directory.
inputs:
  input_1:
    data_path: "/home/viethoang/data/pbmc1/"
    label_path: "/home/viethoang/data/pbmc1/labels.csv"
    obs_tag: "1"

  input_2:
    data_path: "/home/viethoang/data/pbmc2/"
    label_path: "/home/viethoang/data/pbmc2/labels.csv"
    obs_tag: "2"
  
  # input_3:
  #   data_path: "pbmc3/"
  #   label_path: "pbmc3/labels.csv"
  #   obs_tag: "3"


labels: ["label"]


run_on_each_sample: False


# Name of output directory. The path must be either absolute or relative to the
# working directory
output_dir: "/home/viethoang/data/snakemake-single-cell-out"


# List the filter method(s) that will be used. If this is left empty or is deleted,
# then the entire pipeline will be determined by the files in other_outputs
filter_method:
  # - "nofilter"  # No filtering
  - "IQR"


# List the normalization method(s) that will be used.
norm_method:
  - "nonorm"    # No normalization


# List the dimensionality reduction method(s) that will be used.
# Each method must correspond EXACTLY to a function in scripts/dim_reduce.py
# If this is left empty or is deleted, dimensionality reduction as well as 
# everything downstream will not run (ex. clustering).
dim_reduce_method:
  - "pca"
  - "umap"
  # - "tsne"


# List the clustering method(s) that will be used.
# Each method must correspond EXACTLY to a function in scripts/cluster.py
# If this is left empty or is deleted, no clustering will be performed.
# cluster_method:
#   - "leiden"
#   - "louvain"


too-many-cells:

  # make-tree-1:
  #   tmc_qc: True    
  #   options:    
  #     - --filter-thresholds "(200, 1)"
  #     - --draw-collection "PieRing"
  
  # make-tree-2:    
  #   prior: "make-tree-1"
  #   options:
  #     - --draw-node-number
  #     - --dendrogram-output "tree-node-numbers.svg"
  #     - --draw-collection "PieRing"
  #     - --min-size 1
  #     - --smart-cutoff 4

  # make-tree-3:
  #   tmc_qc: False
  #   options:
  #     - --draw-collection "PieRing"
  
  # make-tree-4:
  #   prior: "make-tree-3"
  #   options:
  #     - --draw-collection "PieRing"


# plot_method:

#   scatter:    
#     use_labels: True   
#     dim_reduce:
#       - "pca"
#       - "umap"
#       - "tsne"    
#     cluster:
#       - "leiden"
#       - "louvain"


# Alternatively, list the desired output files. This requires knowledge of the 
# output directory structure and the file naming conventions for this workflow.
other_outputs: