# Example config file for end user.

# User-defined input. The path must be either absolute or relative to the 
# working directory.
input: "data_pbmc/"

label_file:
  # File path must be either absolute or relative to the working directory
  file: "data_pbmc/labels.csv"
  # Labels in the label file that will be used
  labels:
    - "label1"
    - "label2"

# Name of output directory. The path must be either absolute or relative to the
# working directory
output_dir: "data_pbmc/snakemake-single-cell-out"

# List the qc method(s) that will be used. If this is left empty or is deleted,
# then the entire pipeline will be determined by the files in other_outputs
qc_method:
  # - "noqc"
  - "seurat"
  - "tutorial"

# List the dimensionality reduction method(s) that will be used.
# Each method must correspond EXACTLY to a function in scripts/dim_reduce.py
# If this is left empty or is deleted, dimensionality reduction as well as 
# everything downstream will not run (ex. clustering).
dim_reduce_method:
  - "pca"
  - "umap"
  - "tsne"


# List the clustering method(s) that will be used.
# Each method must correspond EXACTLY to a function in scripts/cluster.py
# If this is left empty or is deleted, no clustering will be performed.
cluster_method:
  - "leiden"
  - "louvain"


# NOTE: Future feature
# Plot the results of qc, dimensionality reduction, and clustering
plot_method:

  scatter:    
    use_labels: True   
    dim_reduce:
      - "pca"
      - "umap"
      - "tsne"    
    cluster:
      - "leiden"
      - "louvain"
  
  tree:
    use_labels: True
    dim_reduce:
      - "pca"
      - "umap"
      - "tsne"    
    cluster:
      - "leiden"
      - "louvain"


# Alternatively, list the desired output files. This requires knowledge of the 
# output directory structure and the file naming conventions for this workflow.
other_outputs: