input:
  - "GSM4932159_sample1_barcodes.tsv.gz"
  - "GSM4932159_sample1_genes.tsv.gz"
  - "GSM4932159_sample1_matrix.mtx.gz"

output_dir: "snakemake-single-cell-out"

output_prefix: "GSM4932159_sample1_"

outputs: 
  - "all"