# Example config file for end user.

# # User-defined input. The path must be either absolute or relative to the 
# # working directory.
# inputs:
#   input_1:
#     data_path: "/home/viethoang/data/pbmc/pbmc1/"
#     label_path: "/home/viethoang/data/pbmc/pbmc1/labels.csv"
#     obs_tag: "1"

#   # input_2:
#   #   data_path: "/home/viethoang/data/pbmc/pbmc2/"
#   #   label_path: "/home/viethoang/data/pbmc/pbmc2/labels.csv"
#   #   obs_tag: "2"
  
#   # input_3:
#   #   data_path: "/home/viethoang/data/pbmc/pbmc3/"
#   #   label_path: "/home/viethoang/data/pbmc/pbmc3/labels.csv"
#   #   obs_tag: "3"


# User-defined input. The path must be either absolute or relative to the 
# working directory.
inputs:
  input_1:
    data_path: "/home/viethoang/data/gsi/GSM4121361_DND41_DMSO_scRNA"
    label_path: "/home/viethoang/data/gsi/GSM4121361_DND41_DMSO_scRNA/labels.csv"
    obs_tag: "ctrl"

  input_2:
    data_path: "/home/viethoang/data/gsi/GSM4121362_DND41_GSI_scRNA"
    label_path: "/home/viethoang/data/gsi/GSM4121362_DND41_GSI_scRNA/labels.csv"
    obs_tag: "short"
  
  input_3:
    data_path: "/home/viethoang/data/gsi/GSM4121363_DND41_GSI_Res_ascending"
    label_path: "/home/viethoang/data/gsi/GSM4121363_DND41_GSI_Res_ascending/labels.csv"
    obs_tag: "asc"
  
  input_4:
    data_path: "/home/viethoang/data/gsi/GSM4121364_DND41_GSI_Res_sustained"
    label_path: "/home/viethoang/data/gsi/GSM4121364_DND41_GSI_Res_sustained/labels.csv"
    obs_tag: "sust"


labels: ["label"]


run_on_each_sample: False


# Name of output directory. The path must be either absolute or relative to the
# working directory
# output_dir: "/home/viethoang/data/pbmc/snakemake-single-cell-out"
output_dir: "/home/viethoang/data/gsi/snakemake-single-cell-out"


# List the filter method(s) that will be used. 
filter:
  # - "nofilter"
  IQR:
    k: 1.5
  # zscore: 
    # threshold: [1.96, 1.97]
  # mad: # In development
  # customfilt:


# List the normalization method(s) that will be used.
norm:
  # nonorm:
  # max:
  sum:
  # upper_quartile:
  median:
  # quantile:
  # total_count: # In development
  # log1p:


# List the dimensionality reduction method(s) that will be used.
# Each method must correspond EXACTLY to a function in scripts/dim_reduce.py
# If this is left empty or is deleted, dimensionality reduction as well as 
# everything downstream will not run (ex. clustering).
dim_reduce:
  pca:
  umap:
  tsne:


# List the clustering method(s) that will be used.
# Each method must correspond EXACTLY to a function in scripts/cluster.py
# If this is left empty or is deleted, no clustering will be performed.
cluster:
  leiden:
  # louvain:


# too-many-cells:

#   make-tree-1:
#     tmc_qc: True    
#     options:    
#       - --filter-thresholds "(200, 1)"
#       - --draw-collection "PieRing"
  
#   make-tree-2:    
#     prior: "make-tree-1"
#     options:
#       - --draw-node-number
#       - --dendrogram-output "tree-node-numbers.svg"
#       - --draw-collection "PieRing"
#       - --min-size 1
#       - --smart-cutoff 4

#   make-tree-3:
#     tmc_qc: False
#     options:
#       - --draw-collection "PieRing"
  
#   make-tree-4:
#     prior: "make-tree-3"
#     options:
#       - --draw-collection "PieRing"


plot:
  use_labels: True   
  dim_reduce: True
  cluster: True


differential:

  diff1:
    group1:
      cell_type: ['brain']
      leiden: ['1', '2', '3']
    
    group2:
      cell_type: ['brain']
      leiden: ['4', '5', '6']
  
  diff2:
    one_vs_rest: 'leiden'
    filters:
      cell_type: ['brain', 'liver']
      




# Alternatively, list the desired output files. This requires knowledge of the 
# output directory structure and the file naming conventions for this workflow.
other_outputs: