# Example config file for end user.

# User-defined input. The path must be either absolute or relative to the 
# working directory.
input:
  - "pbmc3k_barcodes.tsv.gz"
  - "pbmc3k_genes.tsv.gz"
  - "pbmc3k_matrix.mtx.gz"

label_file: 
  file: "labels.csv"
  labels:
    - "label1"
    - "label2"

# Name of output directory. The path must be either absolute or relative to the
# working directory
output_dir: "snakemake-single-cell-out"

# The prefix that will be prepended to every output file. Provide an empty 
# string if no prefix is desired.
# TODO: Future functionality -- automatically determine prefix from input files.
# output_prefix: "GSM4932159_sample1_"
output_prefix: "pbmc3k_"

# List the qc method(s) that will be used. If this is left empty or is deleted,
# then the entire pipeline will be determined by the files in other_outputs
qc_method:
  # - "noqc"
  - "seurat"
  - "tutorial"

# List the dimensionality reduction method(s) that will be used.
# Each method must correspond EXACTLY to a function in scripts/dim_reduce.py
# If this is left empty or is deleted, dimensionality reduction as well as 
# everything downstream will not run (ex. clustering).
dim_reduce_method:
  - "pca"
  - "umap"
  - "tsne"


# List the clustering method(s) that will be used.
# Each method must correspond EXACTLY to a function in scripts/cluster.py
# If this is left empty or is deleted, no clustering will be performed.
cluster_method:
  - "leiden"
  - "louvain"


# NOTE: Future feature
# Plot the results of qc, dimensionality reduction, and clustering
plot_method:

  scatter:    
    use_labels: True   
    dim_reduce:
      - "pca"
      - "umap"
      - "tsne"    
    cluster:
      - "leiden"
      - "louvain"
  
  tree:
    use_labels: True
    dim_reduce:
      - "pca"
      - "umap"
      - "tsne"    
    cluster:
      - "leiden"
      - "louvain"


# Alternatively, list the desired output files. This requires knowledge of the 
# output directory structure and the file naming conventions for this workflow.
other_outputs: